print('*______________________________THE PHYSICS NUMERICAL SOLVER______________________________*')
print("Chapter 1. Electric Charges and Fields")
print("Chapter 2. Electrostatic Potential And Capacitance")
print("Chapter 3. Current Electricity")
print("Chapter 4. Moving Charges and Magnetism")
print("Chapter 5. Magnetism and Matter")
print("Chapter 6. Electromagnetic Induction")
print("Chapter 7. Alternating Current")
print("Chapter 8. Electromagnetic Waves")
print("Chapter 9. Ray Optics and Optical Instruments")
print("Chapter 10. Wave Optics")
print("Chapter 11. :Dual Nature of Radiation and Matter")
print("Chapter 12. Atoms")
print("Chapter 13. Nuclei")
print("Chapter 14. Semiconductor Electronics: Materials, Devices, and Simple Circuits")
print("Chapter 15. Communication Systems")
print('++++++++++++++++++++++++++++++++++++++++++++++++++++')
ch= int(input('The Numerical is from Which Chapter___  '))
if ch== 1:
  print('The Numerical is From Electric Field')
  data=0
